name: Check

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  check-schema:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install JSON-Check
        run: pip install json-spec
      - name: Validate Files
        run: |
          json validate --document-file=chapters/02_requirements/product.json
