name: Check

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  check-schema:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Validate JSON
        uses: OrRosenblatt/validate-json-action@0.1.0
        with:
          jsons: [chapters/02_requirements/product.json,
                  chapters/02_requirements/system-hl.json
                  chapters/02_requirements/system-ll.json]