name: Check

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  check-schema:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        file: [ product.xml, system-hl.xml system-ll.xml ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Validate Module
        run: xmllint --schema tools/req_schema.xsd ${{ matrix.file }} -noout
          
